version: "3"
services:
  web:
    volumes:
      - ..:/workspaces:cached

  db:
    image: mysql:8.0
    command: --character-set-server=utf8MB4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: daily-score-db
    volumes:
      - daily-score-data-volume:/var/lib/mysql
    ports:
      - "3308:3306"
